Section.find_or_create_by_name :name=>'Tea', :id=>1
Section.find_or_create_by_name :name=>'Coffee', :id=>2
Section.find_or_create_by_name('Ароматизированный чай')
Section.find_or_create_by_name('На основе черного')
Section.find_or_create_by_name('На основе зеленого')
Section.find_or_create_by_name('Смешанные основы')
Section.find_or_create_by_name('Чайные напитки')
Section.find_or_create_by_name('на основе фруктов')
Section.find_or_create_by_name('на основе руибоса')
Section.find_or_create_by_name('на основе полезных растений')
Section.find_or_create_by_name('на основе мате и лапачо')
Section.find_or_create_by_name('на основе улуна')
Section.find_or_create_by_name('Китайский элитный чай')
Section.find_or_create_by_name('Элитный китайский чай в баночках')
Section.find_or_create_by_name('Белый чай')
Section.find_or_create_by_name('Желтый чай')
Section.find_or_create_by_name('Зеленый чай')
Section.find_or_create_by_name('Красный чай')
Section.find_or_create_by_name('Жасминовый чай')
Section.find_or_create_by_name('Пуэры')
Section.find_or_create_by_name('Улуны материковые (китайские)')
Section.find_or_create_by_name('Связанный чай')
Section.find_or_create_by_name('Традиционные чайные напитки')
Section.find_or_create_by_name('Элитный чай Тайвань')
Section.find_or_create_by_name('Плантационный индийский и цейлонский чай')
Section.find_or_create_by_name('Плантационный черный чай Индия')
Section.find_or_create_by_name('Плантационный черный чай Цейлон')
Section.find_or_create_by_name('Фиточай')
Section.find_or_create_by_name('Чай в пакетиках')
Section.find_or_create_by_name('Чай пакетированный Флёр Деланж')
Section.find_or_create_by_name('Японский чай')
