Section.find_or_create_by_name :name=>'Tea', :id=>1
Section.find_or_create_by_name :name=>'Coffee', :id=>2
Section.find_or_create_by_name(:name=>'Ароматизированный чай', :title=>'Ароматизированный чай')
Section.find_or_create_by_name(:name=>'На основе черного', :title=>'На основе черного')
Section.find_or_create_by_name(:name=>'На основе зеленого', :title=>'На основе зеленого')
Section.find_or_create_by_name(:name=>'Смешанные основы', :title=>'Смешанные основы')
Section.find_or_create_by_name(:name=>'Чайные напитки', :title=>'Чайные напитки')
Section.find_or_create_by_name(:name=>'на основе фруктов', :title=>'на основе фруктов')
Section.find_or_create_by_name(:name=>'на основе руибоса', :title=>'на основе руибоса')
Section.find_or_create_by_name(:name=>'на основе полезных растений', :title=>'на основе полезных растений')
Section.find_or_create_by_name(:name=>'на основе мате и лапачо', :title=>'на основе мате и лапачо')
Section.find_or_create_by_name(:name=>'на основе улуна', :title=>'на основе улуна')
Section.find_or_create_by_name(:name=>'Китайский элитный чай', :title=>'Китайский элитный чай')
Section.find_or_create_by_name(:name=>'Элитный китайский чай в баночках', :title=>'Элитный китайский чай в баночках')
Section.find_or_create_by_name(:name=>'Белый чай', :title=>'Белый чай')
Section.find_or_create_by_name(:name=>'Желтый чай', :title=>'Желтый чай')
Section.find_or_create_by_name(:name=>'Зеленый чай', :title=>'Зеленый чай')
Section.find_or_create_by_name(:name=>'Красный чай', :title=>'Красный чай')
Section.find_or_create_by_name(:name=>'Жасминовый чай', :title=>'Жасминовый чай')
Section.find_or_create_by_name(:name=>'Пуэры', :title=>'Пуэры')
Section.find_or_create_by_name(:name=>'Улуны материковые (китайские)', :title=>'Улуны материковые (китайские)')
Section.find_or_create_by_name(:name=>'Связанный чай', :title=>'Связанный чай')
Section.find_or_create_by_name(:name=>'Традиционные чайные напитки', :title=>'Традиционные чайные напитки')
Section.find_or_create_by_name(:name=>'Элитный чай Тайвань', :title=>'Элитный чай Тайвань')
Section.find_or_create_by_name(:name=>'Плантационный индийский и цейлонский чай', :title=>'Плантационный индийский и цейлонский чай')
Section.find_or_create_by_name(:name=>'Плантационный черный чай Индия', :title=>'Плантационный черный чай Индия')
Section.find_or_create_by_name(:name=>'Плантационный черный чай Цейлон', :title=>'Плантационный черный чай Цейлон')
Section.find_or_create_by_name(:name=>'Фиточай', :title=>'Фиточай')
Section.find_or_create_by_name(:name=>'Чай в пакетиках', :title=>'Чай в пакетиках')
Section.find_or_create_by_name(:name=>'Чай пакетированный Флёр Деланж', :title=>'Чай пакетированный Флёр Деланж')
Section.find_or_create_by_name(:name=>'Японский чай', :title=>'Японский чай')

Section.find_or_create_by_name(:name=>'Barbera', :title=>'Barbera')
Section.find_or_create_by_name(:name=>'Barbera молотый', :title=>'молотый' )
Section.find_or_create_by_name(:name=>'Barbera в зернах', :title=>'в зернах')
Section.find_or_create_by_name(:name=>'Barbera в шоколаде', :title=>'в шоколаде')

Section.find_or_create_by_name(:name=>'Кофе Gut от Gutenberg', :title=>'Кофе Gut от Gutenberg')
Section.find_or_create_by_name(:name=>'Кофе Gut от Gutenberg свежеобжаренный', :title=>'свежеобжаренный')
Section.find_or_create_by_name(:name=>'Кофе Gut от Gutenberg ароматизированный', :title=>'ароматизированный')

Section.find_or_create_by_name(:name=>'зеленый кофе в зернаx', :title=>'зеленый кофе в зернаx')

Section.find_or_create_by_name(:name=>'Bristot', :title=>'Bristot')
Section.find_or_create_by_name(:name=>'Bristot в зернах', :title=>'в зернах')
Section.find_or_create_by_name(:name=>'Bristot молотый', :title=>'молотый')

Section.find_or_create_by_name(:name=>'Malongo', :title=>'Malongo')
Section.find_or_create_by_name(:name=>'Malongo молотый', :title=>'молотый')
Section.find_or_create_by_name(:name=>'Malongo в зернах', :title=>'в зернах')
Section.find_or_create_by_name(:name=>'Malongo растворимый', :title=>'растворимый')

Section.find_or_create_by_name(:name=>'Rombouts', :title=>'Rombouts')
Section.find_or_create_by_name(:name=>'Rombouts в зернах', :title=>'в зернах')
Section.find_or_create_by_name(:name=>'Rombouts молотый', :title=>'молотый')


